"""Autogenerated code to convert list[] to list[]."""

import re
import sys


def convert_file(filename: str) -> None:
    """Convert list[] to list[].

    Args:
        filename: The path to the file to convert.
    """
    with open(filename, encoding="utf-8") as file:
        content = file.read()

    # Replace 'List[' with 'list['
    # This is a simple replacement and might need more sophisticated handling
    # for complex cases or to avoid comments, strings, etc.
    updated_content = re.sub(r"\bList\[(.*?)\]", r"list[\1]", content)

    with open(filename, "w", encoding="utf-8") as file:
        file.write(updated_content)


if __name__ == "__main__":
    for filename in sys.argv[1:]:
        convert_file(filename)
